---
all:
  children:
    app_servers:
      hosts:
        stage-vm:
          ansible_host: "{{ lookup('env', 'STAGE_VM_IP') }}"
          ansible_user: azureuser
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') }}"
          env_name: stage
          acr_name: "{{ lookup('env', 'ACR_NAME') }}"
          app_image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
